version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - ../.env.sample
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: assignment
      POSTGRES_USER: stocky
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db_data:
