name: CI

on:
  push:
    branches: [ master, main, ver1 ]
  pull_request:
    branches: [ master, main, ver1 ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test ./...
      - name: Run golangci-lint
        run: golangci-lint run --timeout 5m
      - name: Build Docker image
        run: docker build -t stocky-backend .
